/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Example1 */

#ifndef _Included_Example1
#define _Included_Example1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Example1
 * Method:    intMethodName
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Example1_intMethodName
  (JNIEnv *, jobject, jint);

/*
 * Class:     Example1
 * Method:    booleanMethodName
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_Example1_booleanMethodName
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Example1
 * Method:    stringMethodName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Example1_stringMethodName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Example1
 * Method:    intArrayMethodName
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Example1_intArrayMethodName
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
